version: '3'
services:
  db:
    image: mysql:8.0-oracle
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portfolio
    ports:
      - '3306:3306'
  app:
    image: golang:1.18
    volumes:
      - .:/app
      - gomod:/go/pkg/mod
volumes:
  gomod:
