AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  portfolio-api
  
  Sample SAM Template for portfolio-api

Parameters:
  DSN:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /portfolio/dsn
  SentryDSN:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /portfolio/sentry/dsn
  AppEnv:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /portfolio/app-env
  ApiKey:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /portfolio/app-key

Globals:
  Function:
    Timeout: 15
    MemorySize: 4096
    Environment:
      Variables:
        DSN: !Ref DSN
        SENTRY_DSN: !Ref SentryDSN
        APP_ENV: !Ref AppEnv
        API_KEY: !Ref ApiKey

Resources:
  DefaultAPI:
    Type: AWS::Serverless::HttpApi
    Properties:
      Domain:
        DomainName: portfolio-api.igsr5.com
        CertificateArn: arn:aws:acm:ap-northeast-1:799705073177:certificate/93205524-ee35-4db3-a2ec-178c97088452
        EndpointConfiguration: REGIONAL
        Route53:
          HostedZoneId: Z10382141794HJUVL4L9O

  # GET:/rss_feeds ===============================================
  GetRSSFeeds:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/get_rss_feeds
      Handler: get_rss_feeds
      Runtime: go1.x
      Architectures:
        - x86_64
      Tracing: Active
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            Path: /rss_feeds
            Method: GET
            ApiId: !Ref DefaultAPI
      Role: !GetAtt LambdaExecutionRole.Arn
  # GET:/rss_feeds ==============================================
 
  # GET:/rss_feed/{id} ==========================================
  GetRSSFeed:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/get_rss_feed
      Handler: get_rss_feed
      Runtime: go1.x
      Architectures:
        - x86_64
      Tracing: Active
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            Path: /rss_feeds/{id}
            Method: GET
            ApiId: !Ref DefaultAPI
      Role: !GetAtt LambdaExecutionRole.Arn
  # GET:/rss_feed/{id} ===========================================

  # POST:/rss_feeds ==============================================
  PostRSSFeed:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/post_rss_feeds
      Handler: post_rss_feeds
      Runtime: go1.x
      Architectures:
        - x86_64
      Tracing: Active
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            Path: /rss_feeds
            Method: POST
            ApiId: !Ref DefaultAPI
      Role: !GetAtt LambdaExecutionRole.Arn
  # POST:/rss_feeds ==============================================
 
  # DELETE:/rss_feed/{id} ========================================
  DeleteRSSFeed:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/delete_rss_feed
      Handler: delete_rss_feed
      Runtime: go1.x
      Architectures:
        - x86_64
      Tracing: Active
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            Path: /rss_feeds/{id}
            Method: DELETE
            ApiId: !Ref DefaultAPI
      Role: !GetAtt LambdaExecutionRole.Arn
  # DELETE:/rss_feed/{id} =========================================
  
  # GET:/blogs ===============================================
  GetBlogs:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/get_blogs
      Handler: get_blogs
      Runtime: go1.x
      Architectures:
        - x86_64
      Tracing: Active
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            Path: /blogs
            Method: GET
            ApiId: !Ref DefaultAPI
      Role: !GetAtt LambdaExecutionRole.Arn
  # GET:/blogs ===============================================
  
  # GET:/blogs/{id} ==========================================
  GetBlog:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/get_blog
      Handler: get_blog
      Runtime: go1.x
      Architectures:
        - x86_64
      Tracing: Active
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            Path: /blogs/{id}
            Method: GET
            ApiId: !Ref DefaultAPI
      Role: !GetAtt LambdaExecutionRole.Arn
  # GET:/blogs/{id} ===========================================

  # POST:/blogs ===============================================
  CreateBlog:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/post_blogs
      Handler: post_blogs
      Runtime: go1.x
      Architectures:
        - x86_64
      Tracing: Active
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            Path: /blogs
            Method: POST
            ApiId: !Ref DefaultAPI
      Role: !GetAtt LambdaExecutionRole.Arn
  # POST:/blogs ===============================================

  # Job: Update Blog Data from rss ============================
  UpdateBlogDataFromRSSJob:
      Type: AWS::Serverless::Function
      Properties:
          CodeUri: job/update_blog_data_from_rss
          Handler: update-blog-data-from-rss
          Runtime: go1.x
          Events:
              UpdateBlogDataFromRSS:
                  Type: Schedule
                  Properties:
                      Schedule: rate(3 minutes)
      Role: !GetAtt LambdaExecutionRole.Arn
  # Job: Update Blog Data from rss ============================
  
  LambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub lambda-execution-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "lambda-secretmanager-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"
              - Effect: "Allow"
                Action:
                    - "ssm:*"
                Resource: "*"
