AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'portfolio-api

  Sample SAM Template for portfolio-api

  '
Parameters:
  DSN:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /portfolio/dsn
  SentryDSN:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /portfolio/sentry/dsn
  AppEnv:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /portfolio/app-env
  ApiKey:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /portfolio/app-key
Globals:
  Function:
    Timeout: 15
    MemorySize: 4096
    Environment:
      Variables:
        DSN:
          Ref: DSN
        SENTRY_DSN:
          Ref: SentryDSN
        APP_ENV:
          Ref: AppEnv
        API_KEY:
          Ref: ApiKey
Resources:
  DefaultAPI:
    Type: AWS::Serverless::HttpApi
    Properties:
      Domain:
        DomainName: portfolio-api.igsr5.com
        CertificateArn: arn:aws:acm:ap-northeast-1:799705073177:certificate/93205524-ee35-4db3-a2ec-178c97088452
        EndpointConfiguration: REGIONAL
        Route53:
          HostedZoneId: Z10382141794HJUVL4L9O
    Metadata:
      SamResourceId: DefaultAPI
  GetRSSFeeds:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://igsr5-portfolio-api-lambda-code/46bc34307491a704321a97ef834cccae
      Handler: get_rss_feeds
      Runtime: go1.x
      Architectures:
      - x86_64
      Tracing: Active
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            Path: /rss_feeds
            Method: GET
            ApiId:
              Ref: DefaultAPI
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
    Metadata:
      SamResourceId: GetRSSFeeds
  GetRSSFeed:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://igsr5-portfolio-api-lambda-code/5505edc04d530a88499145e3f5dc5936
      Handler: get_rss_feed
      Runtime: go1.x
      Architectures:
      - x86_64
      Tracing: Active
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            Path: /rss_feeds/{id}
            Method: GET
            ApiId:
              Ref: DefaultAPI
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
    Metadata:
      SamResourceId: GetRSSFeed
  PostRSSFeed:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://igsr5-portfolio-api-lambda-code/2b88510edc172ed38bc4e8fc87ae03f1
      Handler: post_rss_feeds
      Runtime: go1.x
      Architectures:
      - x86_64
      Tracing: Active
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            Path: /rss_feeds
            Method: POST
            ApiId:
              Ref: DefaultAPI
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
    Metadata:
      SamResourceId: PostRSSFeed
  DeleteRSSFeed:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://igsr5-portfolio-api-lambda-code/13f2628e5d104487e8e27be444733729
      Handler: delete_rss_feed
      Runtime: go1.x
      Architectures:
      - x86_64
      Tracing: Active
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            Path: /rss_feeds/{id}
            Method: DELETE
            ApiId:
              Ref: DefaultAPI
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
    Metadata:
      SamResourceId: DeleteRSSFeed
  GetBlogs:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://igsr5-portfolio-api-lambda-code/37ac0357e143a105ceb190f3aefbf3ba
      Handler: get_blogs
      Runtime: go1.x
      Architectures:
      - x86_64
      Tracing: Active
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            Path: /blogs
            Method: GET
            ApiId:
              Ref: DefaultAPI
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
    Metadata:
      SamResourceId: GetBlogs
  GetBlog:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://igsr5-portfolio-api-lambda-code/e60882399495ed00beacdec8ad96e5fc
      Handler: get_blog
      Runtime: go1.x
      Architectures:
      - x86_64
      Tracing: Active
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            Path: /blogs/{id}
            Method: GET
            ApiId:
              Ref: DefaultAPI
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
    Metadata:
      SamResourceId: GetBlog
  CreateBlog:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://igsr5-portfolio-api-lambda-code/f20bc8bc2fe271a9aef3e83f00c6660e
      Handler: post_blogs
      Runtime: go1.x
      Architectures:
      - x86_64
      Tracing: Active
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            Path: /blogs
            Method: POST
            ApiId:
              Ref: DefaultAPI
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
    Metadata:
      SamResourceId: CreateBlog
  UpdateBlogDataFromRSSJob:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://igsr5-portfolio-api-lambda-code/55fa22c4be5a65d696399b7fe191379e
      Handler: update-blog-data-from-rss
      Runtime: go1.x
      Events:
        UpdateBlogDataFromRSS:
          Type: Schedule
          Properties:
            Schedule: rate(3 minutes)
    Role:
      Fn::GetAtt:
      - LambdaExecutionRole
      - Arn
    Metadata:
      SamResourceId: UpdateBlogDataFromRSSJob
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: lambda-execution-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: lambda-secretmanager-policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: '*'
          - Effect: Allow
            Action:
            - ssm:*
            Resource: '*'
    Metadata:
      SamResourceId: LambdaExecutionRole
