AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'portfolio-api

  Sample SAM Template for portfolio-api

  '
Parameters:
  DSN:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /portfolio/dsn
  SentryDSN:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /portfolio/sentry/dsn
  AppEnv:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /portfolio/app-env
  ApiKey:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /portfolio/app-key
  CloudinaryCloudName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /portfolio/cloudinary-cloud-name
  CloudinaryApiKey:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /portfolio/cloudinary-api-key
  CloudinarySecret:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /portfolio/cloudinary-secret
Globals:
  Function:
    Timeout: 15
    MemorySize: 4096
    Environment:
      Variables:
        DSN:
          Ref: DSN
        SENTRY_DSN:
          Ref: SentryDSN
        APP_ENV:
          Ref: AppEnv
        API_KEY:
          Ref: ApiKey
        CLOUDINARY_CLOUD_NAME:
          Ref: CloudinaryCloudName
        CLOUDINARY_API_KEY:
          Ref: CloudinaryApiKey
        CLOUDINARY_SECRET:
          Ref: CloudinarySecret
Resources:
  DefaultAPI:
    Type: AWS::Serverless::HttpApi
    Properties:
      Domain:
        DomainName: portfolio-api.igsr5.com
        CertificateArn: arn:aws:acm:ap-northeast-1:799705073177:certificate/93205524-ee35-4db3-a2ec-178c97088452
        EndpointConfiguration: REGIONAL
        Route53:
          HostedZoneId: Z10382141794HJUVL4L9O
    Metadata:
      SamResourceId: DefaultAPI
  GetRSSFeeds:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://igsr5-portfolio-api-lambda-code/50c3722defcbd996a75481ef9a43dc3e
      Handler: get_rss_feeds
      Runtime: go1.x
      Architectures:
      - x86_64
      Tracing: Active
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            Path: /rss_feeds
            Method: GET
            ApiId:
              Ref: DefaultAPI
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
    Metadata:
      SamResourceId: GetRSSFeeds
  GetRSSFeed:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://igsr5-portfolio-api-lambda-code/aa8356dc1fdf0d250fd1446f01e7102e
      Handler: get_rss_feed
      Runtime: go1.x
      Architectures:
      - x86_64
      Tracing: Active
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            Path: /rss_feeds/{id}
            Method: GET
            ApiId:
              Ref: DefaultAPI
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
    Metadata:
      SamResourceId: GetRSSFeed
  PostRSSFeed:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://igsr5-portfolio-api-lambda-code/6a43a2f6036808a41a99b64276b5b4df
      Handler: post_rss_feeds
      Runtime: go1.x
      Architectures:
      - x86_64
      Tracing: Active
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            Path: /rss_feeds
            Method: POST
            ApiId:
              Ref: DefaultAPI
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
    Metadata:
      SamResourceId: PostRSSFeed
  DeleteRSSFeed:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://igsr5-portfolio-api-lambda-code/70bc1dd2aa47f4355edf356c3ae73ee0
      Handler: delete_rss_feed
      Runtime: go1.x
      Architectures:
      - x86_64
      Tracing: Active
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            Path: /rss_feeds/{id}
            Method: DELETE
            ApiId:
              Ref: DefaultAPI
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
    Metadata:
      SamResourceId: DeleteRSSFeed
  GetBlogs:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://igsr5-portfolio-api-lambda-code/227b06b373da8446ffb3322e174b8d48
      Handler: get_blogs
      Runtime: go1.x
      Architectures:
      - x86_64
      Tracing: Active
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            Path: /blogs
            Method: GET
            ApiId:
              Ref: DefaultAPI
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
    Metadata:
      SamResourceId: GetBlogs
  GetBlog:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://igsr5-portfolio-api-lambda-code/586d40e58bc47bacee415905e9c3606e
      Handler: get_blog
      Runtime: go1.x
      Architectures:
      - x86_64
      Tracing: Active
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            Path: /blogs/{id}
            Method: GET
            ApiId:
              Ref: DefaultAPI
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
    Metadata:
      SamResourceId: GetBlog
  CreateBlog:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://igsr5-portfolio-api-lambda-code/ab0be77d4a3e79bf8adcb4efbcab6528
      Handler: post_blogs
      Runtime: go1.x
      Architectures:
      - x86_64
      Tracing: Active
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            Path: /blogs
            Method: POST
            ApiId:
              Ref: DefaultAPI
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
    Metadata:
      SamResourceId: CreateBlog
  UpdateBlogDataFromRSSJob:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://igsr5-portfolio-api-lambda-code/1a945e18de3929203037ff46b60521f4
      Handler: update-blog-data-from-rss
      Runtime: go1.x
      Events:
        UpdateBlogDataFromRSS:
          Type: Schedule
          Properties:
            Schedule: rate(3 minutes)
    Role:
      Fn::GetAtt:
      - LambdaExecutionRole
      - Arn
    Metadata:
      SamResourceId: UpdateBlogDataFromRSSJob
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: lambda-execution-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: lambda-secretmanager-policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: '*'
          - Effect: Allow
            Action:
            - ssm:*
            Resource: '*'
    Metadata:
      SamResourceId: LambdaExecutionRole
