AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'portfolio-api

  Sample SAM Template for portfolio-api

  '
Parameters:
  DSN:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /portfolio/dsn
  SentryDSN:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /portfolio/sentry/dsn
  AppEnv:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /portfolio/app-env
Globals:
  Function:
    Timeout: 15
    MemorySize: 4096
    Environment:
      Variables:
        DSN:
          Ref: DSN
        SENTRY_DSN:
          Ref: SentryDSN
        APP_ENV:
          Ref: AppEnv
Resources:
  DefaultAPI:
    Type: AWS::Serverless::HttpApi
    Properties:
      Domain:
        DomainName: portfolio-api.igsr5.com
        CertificateArn: arn:aws:acm:ap-northeast-1:799705073177:certificate/93205524-ee35-4db3-a2ec-178c97088452
        EndpointConfiguration: REGIONAL
        Route53:
          HostedZoneId: Z10382141794HJUVL4L9O
    Metadata:
      SamResourceId: DefaultAPI
  GetRSSFeeds:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://igsr5-portfolio-api-lambda-code/07849ab703719ad6c2b80ff5c6abd85d
      Handler: get_rss_feed
      Runtime: go1.x
      Architectures:
      - x86_64
      Tracing: Active
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            Path: /rss_feed/{id}
            Method: GET
            ApiId:
              Ref: DefaultAPI
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
    Metadata:
      SamResourceId: GetRSSFeeds
  PostRSSFeeds:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://igsr5-portfolio-api-lambda-code/36bf143914c3da7117798b4105eb9596
      Handler: post_rss_feeds
      Runtime: go1.x
      Architectures:
      - x86_64
      Tracing: Active
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            Path: /rss_feeds
            Method: POST
            ApiId:
              Ref: DefaultAPI
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
    Metadata:
      SamResourceId: PostRSSFeeds
  UpdateBlogDataFromRSSJob:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://igsr5-portfolio-api-lambda-code/f2d375e075fa2e6e39589878693d0f0f
      Handler: update-blog-data-from-rss
      Runtime: go1.x
      Events:
        UpdateBlogDataFromRSS:
          Type: Schedule
          Properties:
            Schedule: cron(* * * * ? *)
    Environment:
      Variables:
        DSN:
          Ref: DSN
    Role:
      Fn::GetAtt:
      - LambdaExecutionRole
      - Arn
    Metadata:
      SamResourceId: UpdateBlogDataFromRSSJob
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: lambda-execution-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: lambda-secretmanager-policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: '*'
          - Effect: Allow
            Action:
            - ssm:*
            Resource: '*'
    Metadata:
      SamResourceId: LambdaExecutionRole
