name: 'Deploy'
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0 
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Terraform init
        run: terraform init
        working-directory: terraform
      - name: Terraform plan
        run: terraform plan
        working-directory: terraform
      - name: deploy
        run: make package
