name: 'Deploy'
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0 
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Terraform init
        run: terraform init
        working-directory: terraform
      - name: Terraform plan
        run: terraform plan
        working-directory: terraform
      - name: deploy
        run: make package
      - name: check diff
        id: diff
        continue-on-error: true
        run: |
          git add -N .
          git diff --exit-code
      - name: Create PR
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Update terraform/template.yml by deploy"
          branch: update-template.yml-by-deploy
          base: "master"
          body: ""
          branch-suffix: "timestamp"
          delete-branch: true
          title: "Update terraform/template.yml by deploy"
        if: steps.diff.outcome == 'failure'
      - name: PR merge
        run: gh pr merge ${{ steps.cpr.outputs.pull-request-number }} -m -d
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        if: steps.diff.outcome == 'failure'
